version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    container_name: node-app
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
volumes:
  mongo-data:
